# Generated by Django 5.0.2 on 2024-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='outros',
            field=models.CharField(max_length=15000),
        ),
    ]
