# Generated by Django 5.0.2 on 2024-02-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0003_rename_word_templates_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='ano_vigencia',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
