# Generated by Django 4.1.9 on 2024-02-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0004_templates_ano_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='bairro',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='cep',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='cidade_endereco',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='complemento',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='endereco',
            field=models.CharField(default='', max_length=550),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='uf_endereco',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='outros',
            field=models.CharField(max_length=25000),
        ),
        migrations.AlterField(
            model_name='templates',
            name='ano_vigencia',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=4),
        ),
    ]
