# Generated by Django 4.1.9 on 2024-02-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0005_contrato_bairro_contrato_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cambio_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cambio_valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_de_assinatura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_de_inicio_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_de_recebimento_da_oferta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_do_fim_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dias_vigencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='outros',
            field=models.CharField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='taxa_inicial_franquia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='uf_pretendido',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True),
        ),
    ]
