# Generated by Django 4.1.9 on 2024-02-27 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissao', '0006_alter_contrato_cambio_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFDMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_de_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('cnpj', models.CharField(max_length=18)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('early_toddler_qtd', models.IntegerField(blank=True, null=True)),
                ('early_toddler_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('toddler_qtd', models.IntegerField(blank=True, null=True)),
                ('toddler_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('nursery_qtd', models.IntegerField(blank=True, null=True)),
                ('nursery_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('junior_kindergarten_qtd', models.IntegerField(blank=True, null=True)),
                ('junior_kindergarten_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('senior_kindergarten_qtd', models.IntegerField(blank=True, null=True)),
                ('senior_kindergarten_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_1_qtd', models.IntegerField(blank=True, null=True)),
                ('year_1_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_2_qtd', models.IntegerField(blank=True, null=True)),
                ('year_2_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_3_qtd', models.IntegerField(blank=True, null=True)),
                ('year_3_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_4_qtd', models.IntegerField(blank=True, null=True)),
                ('year_4_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_5_qtd', models.IntegerField(blank=True, null=True)),
                ('year_5_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_6_qtd', models.IntegerField(blank=True, null=True)),
                ('year_6_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_7_qtd', models.IntegerField(blank=True, null=True)),
                ('year_7_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_8_qtd', models.IntegerField(blank=True, null=True)),
                ('year_8_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_9_qtd', models.IntegerField(blank=True, null=True)),
                ('year_9_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_10_qtd', models.IntegerField(blank=True, null=True)),
                ('year_10_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_11_qtd', models.IntegerField(blank=True, null=True)),
                ('year_11_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('year_12_qtd', models.IntegerField(blank=True, null=True)),
                ('year_12_vm', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('usuario_modificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
