# Generated by Django 4.1.9 on 2024-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0007_avaliacaofdmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='early_toddler_qtd',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
