# Generated by Django 4.1.9 on 2024-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0008_alter_avaliacaofdmp_early_toddler_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='early_toddler_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='early_toddler_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='junior_kindergarten_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='junior_kindergarten_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='nursery_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='nursery_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='senior_kindergarten_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='senior_kindergarten_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='toddler_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='toddler_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_10_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_10_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_11_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_11_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_12_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_12_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_1_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_1_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_2_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_2_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_3_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_3_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_4_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_4_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_5_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_5_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_6_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_6_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_7_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_7_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_8_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_8_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_9_qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_9_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True),
        ),
    ]
