# Generated by Django 4.1.9 on 2024-02-28 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0009_alter_avaliacaofdmp_early_toddler_qtd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaofdmp',
            old_name='early_toddler_qtd',
            new_name='bear_care_qtd',
        ),
        migrations.RenameField(
            model_name='avaliacaofdmp',
            old_name='early_toddler_vm',
            new_name='bear_care_vm',
        ),
    ]
