# Generated by Django 4.1.9 on 2024-02-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0011_avaliacaofdmp_cargo_avaliacaofdmp_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofdmp',
            name='bloqueado_para_edicao',
            field=models.BooleanField(default=False, verbose_name='Bloqueado para Edição'),
        ),
    ]
