# Generated by Django 4.1.9 on 2024-03-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0012_avaliacaofdmp_bloqueado_para_edicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
