# Generated by Django 4.1.9 on 2024-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0013_alter_avaliacaofdmp_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='bear_care_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Bear Care - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='bear_care_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Bear Care - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='toddler_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Toddler - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='toddler_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Toddler - Valor Médio da Mensalidade'),
        ),
    ]
