# Generated by Django 4.1.9 on 2024-03-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissao', '0014_alter_avaliacaofdmp_bear_care_qtd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaofdmp',
            name='data_de_criacao',
        ),
        migrations.RemoveField(
            model_name='avaliacaofdmp',
            name='data_de_modificacao',
        ),
        migrations.RemoveField(
            model_name='avaliacaofdmp',
            name='usuario_modificacao',
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='cargo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='junior_kindergarten_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Junior Kindergarten - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='junior_kindergarten_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Junior Kindergarten - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='nursery_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nursery - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='nursery_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Nursery - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='razao_social',
            field=models.CharField(max_length=200, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='senior_kindergarten_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Senior Kindergarten - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='senior_kindergarten_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Senior Kindergarten - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_10_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 10 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_10_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 10 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_11_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 11 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_11_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 11 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_12_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 12 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_12_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 12 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_1_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 1 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_1_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 1 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_2_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 2 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_2_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 2 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_3_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 3 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_3_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 3 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_4_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 4 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_4_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 4 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_5_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 5 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_5_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 5 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_6_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 6 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_6_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 6 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_7_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 7 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_7_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 7 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_8_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 8 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_8_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 8 - Valor Médio da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_9_qtd',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Year 9 - Quantidade de Alunos'),
        ),
        migrations.AlterField(
            model_name='avaliacaofdmp',
            name='year_9_vm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=25, null=True, verbose_name='Year 9 - Valor Médio da Mensalidade'),
        ),
    ]
